/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Category Configuration Content
 * This file contains all category definitions for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Generated: 2025-12-22T21:21:35.440Z
 */

import type { Category } from './categories.schema'

/**
 * Blog categories with nested subcategories
 * Auto-populated from brand database (BrandCategory table)
 */
export const categories: Category[] = [
  {
    id: "b1b96368-9137-434d-a646-005701dad4f6",
    name: "Espresso Machines",
    slug: "espresso-machines",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "f82d0829-89bd-43e3-a4e6-e8aaba13ba3f",
        name: "Semi-Automatic",
        slug: "semi-automatic",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "c7bc958c-b4d5-4843-8bbf-00aaa470f9d7",
        name: "Automatic/Super Automatic",
        slug: "automaticsuper-automatic",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "e24214af-f5ff-4bf8-b2db-7e628ac0e156",
        name: "Manual/Lever",
        slug: "manuallever",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "e091d682-5588-48ef-96aa-5da765dc364f",
        name: "Portable Espresso",
        slug: "portable-espresso",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "a69c4f92-162d-421d-b305-383698d30055",
    name: "Coffee Makers",
    slug: "coffee-makers",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "39c659d6-6000-4f7e-a14c-caf6c0381469",
        name: "Drip Coffee Makers",
        slug: "drip-coffee-makers",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "6b4e5f15-3f85-44d5-994d-3b093d31e290",
        name: "Pour-Over Brewers",
        slug: "pour-over-brewers",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "853be739-c7ec-4c04-b64f-5c41990120a1",
        name: "French Press",
        slug: "french-press",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "c4950758-3571-4388-a1d3-875faf70305a",
        name: "AeroPress Style",
        slug: "aeropress-style",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "4e5c622b-c7c9-4cb3-bb12-449320ddafa5",
        name: "Cold Brew Systems",
        slug: "cold-brew-systems",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "48844c10-7c9d-4b9a-941a-a020c22960f3",
        name: "Moka Pots",
        slug: "moka-pots",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "204f55e0-0e8a-4b5e-a332-f074c75744ad",
    name: "Grinders",
    slug: "grinders",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "d38e70ff-268c-43f8-856f-66fcb8f19dd0",
        name: "Burr Grinders",
        slug: "burr-grinders",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "2c173dba-9d51-43a6-853e-93a57e0e53f4",
        name: "Blade Grinders",
        slug: "blade-grinders",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "cf99cd90-260f-4c1e-afc3-4e854ad2d47b",
        name: "Espresso-Focused Grinders",
        slug: "espresso-focused-grinders",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "c67e41fd-e008-4b11-a682-344ee27696ac",
        name: "Hand Grinders",
        slug: "hand-grinders",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "66c16258-a634-454e-aeae-3729a2a527f8",
        name: "Single-Dose Grinders",
        slug: "single-dose-grinders",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "72d4a110-a04c-4d5d-98cb-4aa2c21fd451",
    name: "Espresso Tools",
    slug: "espresso-tools",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "add29166-779c-49fe-8163-d14ae7132183",
        name: "WDT Tools",
        slug: "wdt-tools",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "9a6057d3-7324-4c38-ad05-82e965956cf8",
        name: "Tampers & Distributors",
        slug: "tampers--distributors",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "b35b7e0b-fd2d-4894-a778-1fdaded325ce",
        name: "Scales & Timers",
        slug: "scales--timers",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "42a93cab-5f51-4ebb-9a7d-3f62eecc53f2",
        name: "Portafilters & Baskets",
        slug: "portafilters--baskets",
        showInHeader: true,
        showInFooter: true
      }
    ]
  }
]
