/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Site Configuration Content
 * This file contains all customizable values for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Brand: The Brew Master
 * Generated: 2025-12-22T21:21:35.440Z
 */

import type { SiteConfigSchema, ColorConfigSchema } from './config.schema'

/**
 * Main site configuration
 * Values auto-populated from brand database
 */
export const siteContent: SiteConfigSchema = {
  // Brand identity
  brand: {
    id: "bf9ae956-90d2-423b-ba89-75c76a45f165",
    name: "The Brew Master",
    description: "BrewMaster Hub empowers coffee enthusiasts with expert insights, innovative brewing techniques, and the latest industry trends, elevating every coffee experience from novice to connoisseur.",
    url: "https://the-brew-master-blog.vercel.app",
    logoPath: "/logo.jpg",
    faviconPath: "/logo.jpg",
    ogImagePath: "/logo.jpg",
    mainAppUrl: "https://app.thefaceless.ai",
    legalEmail: "support@banedigital.com",
    privacyEmail: "support@banedigital.com",
    tagline: "Elevate your brew with expert insights and innovative techniques"
  },

  // Homepage hero section
  hero: {
    title: "Welcome to The Brew Master",
    subtitle: "Elevate your brew with expert insights and innovative techniques"
  },

  // Default author information
  author: {
    name: "The Brew Master Team",
    bio: "BrewMaster Hub empowers coffee enthusiasts with expert insights, innovative brewing techniques, and the latest industry trends, elevating every cof...",
    role: "Content Creator",
    image: "/logo.jpg"
  },

  // Section headings throughout the site
  sections: {
    topArticles: {
      title: "Featured Articles",
      description: "Handpicked posts just for you"
    },
    recentPosts: {
      title: "Latest Posts"
    },
    categories: {
      title: "Explore Specialty Coffee & Espresso Topics"
    }
  },

  // Newsletter subscription section
  newsletter: {
    title: "Stay Updated",
    description: "Get the latest from The Brew Master delivered to your inbox",
    disclaimer: "Unsubscribe anytime. We respect your privacy."
  },

  // Blog categories (from brand database)
  categories: [
    { 
      name: "Semi-Automatic",
      icon: "FileText",
      slug: "semi-automatic"
    },
    { 
      name: "Drip Coffee Makers",
      icon: "FileText",
      slug: "drip-coffee-makers"
    },
    { 
      name: "Espresso Machines",
      icon: "FileText",
      slug: "espresso-machines"
    },
    { 
      name: "Coffee Makers",
      icon: "FileText",
      slug: "coffee-makers"
    },
    { 
      name: "Burr Grinders",
      icon: "FileText",
      slug: "burr-grinders"
    },
    { 
      name: "Pour-Over Brewers",
      icon: "FileText",
      slug: "pour-over-brewers"
    }
  ],

  // All authors for this brand (with AI-generated portraits)
  authors: [
    {
      id: "a7a45b37-73a5-4710-bf6c-086ab1a56cff",
      name: "Sofia Hartwell",
      bio: "Sofia brings her global perspective and cultural insights to her engaging and thought-provoking articles. Her fascination with the social and historical aspects of coffee culture allows her to craft stories that connect readers to the rich tapestry of coffee traditions around the world, while her interviews and reviews provide a fresh and authentic voice in the industry.",
      image: "/authors/a7a45b37-73a5-4710-bf6c-086ab1a56cff.jpg",
      role: "Coffee Culture Curator"
    },
    {
      id: "eb008c73-763b-43d2-9414-c886d41348e0",
      name: "Liam Voss",
      bio: "Liam's writing is infused with technical precision and a sprinkle of humor, reflecting his background as an engineer turned espresso expert. He loves diving into the mechanics of coffee machines and sharing innovative brewing techniques, making him the go-to author for readers looking to elevate their home brewing skills with a touch of geeky enthusiasm.",
      image: "/authors/eb008c73-763b-43d2-9414-c886d41348e0.jpg",
      role: "Espresso Engineer"
    },
    {
      id: "ee7af99e-67c3-44fe-ac5e-46d3326a3ead",
      name: "Emma Mercer",
      bio: "Emma combines her deep knowledge of coffee with a warm, approachable writing style that makes complex topics accessible to all. Her expertise in coffee tasting and brewing techniques is matched by her passion for sharing practical tips and insights, making her a trusted voice for both novices and seasoned coffee enthusiasts alike.",
      image: "/authors/ee7af99e-67c3-44fe-ac5e-46d3326a3ead.jpg",
      role: "Certified Coffee Sommelier"
    }
  ]
}

/**
 * Color configuration
 * Brand colors in oklch() format for consistent rendering
 * Auto-converted from brand hex colors
 */
export const colorContent: ColorConfigSchema = {
  // Light mode colors
  light: {
    primary: "#2563EB",      // #2563EB
    secondary: "#64748B",  // #64748B
    accent: "#F59E0B"         // #F59E0B
  },

  // Dark mode colors (auto-lightened for contrast)
  dark: {
    primary: "#2563EB",
    secondary: "#64748B",
    accent: "#F59E0B"
  }
}
